import type { StremioManifest } from "../stremio/manifest";

export const FXGGXT_CATALOG_MAP: Record<string, { path: string; name: string }> = {
  "fxggxt-amateur": { path: "/tag/amateur-gay-porn/", name: "Fxg-Amateur" },
  "fxggxt-bareback": { path: "/tag/bareback-gay-porn/", name: "Fxg-Bareback" },
  "fxggxt-big-dick": { path: "/tag/big-dick-gay-porn/", name: "Fxg-Big Dick" },
  "fxggxt-bisexual": { path: "/tag/bisexual-porn/", name: "Fxg-Bisexual" },
  "fxggxt-group": { path: "/tag/group-gay-porn/", name: "Fxg-Group" },
  "fxggxt-hunk": { path: "/tag/hunk-gay-porn-videos/", name: "Fxg-Hunk" },
  "fxggxt-interracial": { path: "/tag/interracial-gay-porn/", name: "Fxg-Interracial" },
  "fxggxt-muscle": { path: "/tag/muscle-gay-porn/", name: "Fxg-Muscle" },
  "fxggxt-straight": { path: "/tag/straight-guys-gay-porn/", name: "Fxg-Straight" },
  "fxggxt-twink": { path: "/tag/twink-gay-porn/", name: "Fxg-Twink" },
  "fxggxt-4myfans": { path: "/category/4-myfans/", name: "Fxg-4MyFans" },
  "fxggxt-activeduty": { path: "/category/active-duty/", name: "Fxg-ActiveDuty" },
  "fxggxt-adulttime": { path: "/category/adulttime/", name: "Fxg-AdultTime" },
  "fxggxt-allaustralianboys": { path: "/category/allaustralianboys/", name: "Fxg-AllAustralianBoys" },
  "fxggxt-amateurgaypov": { path: "/category/amateurgaypov/", name: "Fxg-AmateurGayPOV" },
  "fxggxt-amateursdoit": { path: "/category/amateursdoit/", name: "Fxg-AmateursDoIt" },
  "fxggxt-american-muscle-hunks": { path: "/category/american-muscle-hunks/", name: "Fxg-American Muscle Hunks" },
  "fxggxt-andolinixxl": { path: "/category/andolinixxl/", name: "Fxg-AndoliniXXL" },
  "fxggxt-asgmax": { path: "/category/asgmax/", name: "Fxg-ASGMax" },
  "fxggxt-badpuppy": { path: "/category/badpuppy/", name: "Fxg-BadPuppy" },
  "fxggxt-baitbuddies": { path: "/category/baitbuddies/", name: "Fxg-BaitBuddies" },
  "fxggxt-baitbus": { path: "/category/baitbus/", name: "Fxg-BaitBus" },
  "fxggxt-barebackthathole": { path: "/category/barebackthathole/", name: "Fxg-BarebackThatHole" },
  "fxggxt-beefcakehunter": { path: "/category/beefcake-hunter/", name: "Fxg-BeefCakeHunter" },
  "fxggxt-bel-ami": { path: "/category/bel-ami/", name: "Fxg-BelAmi" },
  "fxggxt-bentleyrace": { path: "/category/bentleyrace/", name: "Fxg-BentleyRace" },
  "fxggxt-biguysfuck": { path: "/category/bi-guys-fuck/", name: "Fxg-BiGuysFuck" },
  "fxggxt-bilatinmen": { path: "/category/bi-latin-men/", name: "Fxg-BiLatinMen" },
  "fxggxt-blacksonboys": { path: "/category/blacksonboys/", name: "Fxg-BlacksOnBoys" },
  "fxggxt-blakemason": { path: "/category/blakemason/", name: "Fxg-BlakeMason" },
  "fxggxt-boys-halfway-house": { path: "/category/boys-halfway-house/", name: "Fxg-Boys Halfway House" },
  "fxggxt-brandtsboys": { path: "/category/brandtsboys/", name: "Fxg-BrandtsBoys" },
  "fxggxt-bravofucker": { path: "/category/bravofucker/", name: "Fxg-BravoFucker" },
  "fxggxt-breederbros": { path: "/category/breederbros/", name: "Fxg-BreederBros" },
  "fxggxt-breedmeraw": { path: "/category/breedmeraw/", name: "Fxg-BreedMeRaw" },
  "fxggxt-bring-me-a-boy": { path: "/category/bring-me-a-boy/", name: "Fxg-Bring Me A Boy" },
  "fxggxt-brokestraightboys": { path: "/category/brokestraightboys/", name: "Fxg-BrokeStraightBoys" },
  "fxggxt-bromo": { path: "/category/bromo/", name: "Fxg-Bromo" },
  "fxggxt-brothercrush": { path: "/category/say-uncle/brothercrush/", name: "Fxg-BrotherCrush" },
  "fxggxt-brz-studios": { path: "/category/brz-studios/", name: "Fxg-BRZ Studios" },
  "fxggxt-bullyhim": { path: "/category/say-uncle/bullyhim/", name: "Fxg-BullyHim" },
  "fxggxt-chaosmen": { path: "/category/chaos-men/", name: "Fxg-ChaosMen" },
  "fxggxt-citebeur": { path: "/category/citebeur/", name: "Fxg-Citebeur" },
  "fxggxt-club-inferno-dungeon": { path: "/category/club-inferno-dungeon/", name: "Fxg-Club Inferno Dungeon" },
  "fxggxt-clubamateurusa": { path: "/category/clubamateurusa/", name: "Fxg-ClubAmateurUSA" },
  "fxggxt-clubbangboys": { path: "/category/clubbangboys/", name: "Fxg-ClubBangBoys" },
  "fxggxt-cocksuremen": { path: "/category/cocksuremen/", name: "Fxg-CockSureMen" },
  "fxggxt-cockyboys": { path: "/category/cocky-boys/", name: "Fxg-CockyBoys" },
  "fxggxt-colbyknox": { path: "/category/colbyknox/", name: "Fxg-ColbyKnox" },
  "fxggxt-collegeboyphysicals": { path: "/category/collegeboyphysicals/", name: "Fxg-CollegeBoyPhysicals" },
  "fxggxt-collegedudes": { path: "/category/collegedudes/", name: "Fxg-CollegeDudes" },
  "fxggxt-corbin-fisher": { path: "/category/corbin-fisher/", name: "Fxg-CorbinFisher" },
  "fxggxt-creamybros": { path: "/category/creamybros/", name: "Fxg-CreamyBros" },
  "fxggxt-crunchboy": { path: "/category/crunchboy/", name: "Fxg-CrunchBoy" },
  "fxggxt-cumdumpsluts": { path: "/category/cumdumpsluts/", name: "Fxg-CumDumpSluts" },
  "fxggxt-cutlersden": { path: "/category/cutlersden/", name: "Fxg-CutlersDen" },
  "fxggxt-czech-hunter": { path: "/category/czech-hunter/", name: "Fxg-Czech Hunter" },
  "fxggxt-dadcreep": { path: "/category/say-uncle/dadcreep/", name: "Fxg-DadCreep" },
  "fxggxt-deviantotter": { path: "/category/deviantotter/", name: "Fxg-DeviantOtter" },
  "fxggxt-devilsfilm": { path: "/category/devilsfilm/", name: "Fxg-DevilsFilm" },
  "fxggxt-dickrides": { path: "/category/say-uncle/dickrides/", name: "Fxg-DickRides" },
  "fxggxt-dirty-scout": { path: "/category/dirty-scout/", name: "Fxg-Dirty Scout" },
  "fxggxt-disruptivefilms": { path: "/category/disruptivefilms/", name: "Fxg-DisruptiveFilms" },
  "fxggxt-doctortapes": { path: "/category/say-uncle/doctortapes/", name: "Fxg-DoctorTapes" },
  "fxggxt-dudesraw": { path: "/category/dudesraw/", name: "Fxg-DudesRaw" },
  "fxggxt-eastboys": { path: "/category/eastboys/", name: "Fxg-EastBoys" },
  "fxggxt-englishlads": { path: "/category/englishlads/", name: "Fxg-EnglishLads" },
  "fxggxt-ericvideos": { path: "/category/ericvideos/", name: "Fxg-EricVideos" },
  "fxggxt-euroboyxxx": { path: "/category/euroboyxxx/", name: "Fxg-EuroBoyXXX" },
  "fxggxt-europeenz": { path: "/category/say-uncle/europeenz/", name: "Fxg-EuroPeenz" },
  "fxggxt-extrabigdicks": { path: "/category/pride-studios/extrabigdicks/", name: "Fxg-ExtraBigDicks" },
  "fxggxt-facedownassup": { path: "/category/facedownassup/", name: "Fxg-FaceDownAssUp" },
  "fxggxt-falcon-studios": { path: "/category/falcon-studios/", name: "Fxg-FalconStudios" },
  "fxggxt-familycreep": { path: "/category/pride-studios/familycreep/", name: "Fxg-FamilyCreep" },
  "fxggxt-familycuckolds": { path: "/category/familycuckolds/", name: "Fxg-FamilyCuckolds" },
  "fxggxt-familydick": { path: "/category/say-uncle/familydick/", name: "Fxg-FamilyDick" },
  "fxggxt-fetishforce": { path: "/category/fetishforce/", name: "Fxg-FetishForce" },
  "fxggxt-fitcasting": { path: "/category/fitcasting/", name: "Fxg-FitCasting" },
  "fxggxt-fraternity-x": { path: "/category/fraternity-x/", name: "Fxg-FraternityX" },
  "fxggxt-frenchdudes": { path: "/category/frenchdudes/", name: "Fxg-FrenchDudes" },
  "fxggxt-frenchtwinks": { path: "/category/frenchtwinks/", name: "Fxg-FrenchTwinks" },
  "fxggxt-freshmen": { path: "/category/freshmen/", name: "Fxg-FreshMen" },
  "fxggxt-fuckermate": { path: "/category/fuckermate/", name: "Fxg-FuckerMate" },
  "fxggxt-gaycest": { path: "/category/gaycest/", name: "Fxg-GayCest" },
  "fxggxt-gay-hoopla": { path: "/category/gay-hoopla/", name: "Fxg-GayHoopla" },
  "fxggxt-gayroom": { path: "/category/gayroom/", name: "Fxg-GayRoom" },
  "fxggxt-grindhouseraw": { path: "/category/grindhouseraw/", name: "Fxg-GrindHouseRaw" },
  "fxggxt-guybone": { path: "/category/guybone/", name: "Fxg-GuyBone" },
  "fxggxt-guyselector": { path: "/category/guyselector/", name: "Fxg-GuySelector" },
  "fxggxt-guysinsweatpants": { path: "/category/guysinsweatpants/", name: "Fxg-GuysInSweatpants" },
  "fxggxt-helixstudios": { path: "/category/helixstudios/", name: "Fxg-HelixStudios" },
  "fxggxt-himerostv": { path: "/category/himerostv/", name: "Fxg-HimerosTV" },
  "fxggxt-hotboys-brazil": { path: "/category/hotboys-brazil/", name: "Fxg-HotBoys Brazil" },
  "fxggxt-hotdadshotlads": { path: "/category/hotdadshotlads/", name: "Fxg-HotDadsHotLads" },
  "fxggxt-hot-guys-fuck": { path: "/category/hot-guys-fuck/", name: "Fxg-HotGuysFuck" },
  "fxggxt-hothouse": { path: "/category/hothouse/", name: "Fxg-HotHouse" },
  "fxggxt-hotoldermale": { path: "/category/hotoldermale/", name: "Fxg-HotOlderMale" },
  "fxggxt-hungfuckers": { path: "/category/hungfuckers/", name: "Fxg-HungFuckers" },
  "fxggxt-hungpapi": { path: "/category/hungpapi/", name: "Fxg-HungPapi" },
  "fxggxt-hungyoungbrit": { path: "/category/hungyoungbrit/", name: "Fxg-HungYoungBrit" },
  "fxggxt-hunk-channel": { path: "/category/hunk-channel/", name: "Fxg-Hunk Channel" },
  "fxggxt-iconmale": { path: "/category/iconmale/", name: "Fxg-IconMale" },
  "fxggxt-iomacho": { path: "/category/iomacho/", name: "Fxg-IOMacho" },
  "fxggxt-irmaosdotados": { path: "/category/irmaosdotados/", name: "Fxg-IrmaosDotados" },
  "fxggxt-jalifstudio": { path: "/category/jalifstudio/", name: "Fxg-JalifStudio" },
  "fxggxt-jasonsparkslive": { path: "/category/jasonsparkslive/", name: "Fxg-JasonSparksLive" },
  "fxggxt-jawked": { path: "/category/jawked/", name: "Fxg-Jawked" },
  "fxggxt-johnnyrapid": { path: "/category/johnnyrapid/", name: "Fxg-JohnnyRapid" },
  "fxggxt-just-for-fans": { path: "/category/just-for-fans/", name: "Fxg-JustForFans" },
  "fxggxt-kinkmen": { path: "/category/kinkmen/", name: "Fxg-KinkMen" },
  "fxggxt-kristenbjorn": { path: "/category/kristenbjorn/", name: "Fxg-KristenBjorn" },
  "fxggxt-latinboyz": { path: "/category/latinboyz/", name: "Fxg-LatinBoyz" },
  "fxggxt-latinleche": { path: "/category/say-uncle/latinleche/", name: "Fxg-LatinLeche" },
  "fxggxt-latinloads": { path: "/category/treasure-island-media/latinloads/", name: "Fxg-LatinLoads" },
  "fxggxt-latinoguysporn": { path: "/category/say-uncle/latinoguysporn/", name: "Fxg-LatinoGuysPorn" },
  "fxggxt-slowteasinghandjobs": { path: "/category/slowteasinghandjobs/", name: "Fxg-SlowTeasingHandJobs" },
  "fxggxt-southernstrokes": { path: "/category/southernstrokes/", name: "Fxg-SouthernStrokes" },
  "fxggxt-spritzz": { path: "/category/spritzz/", name: "Fxg-Spritzz" },
  "fxggxt-spunkworthy": { path: "/category/spunkworthy/", name: "Fxg-SpunkWorthy" },
  "fxggxt-stagcollective": { path: "/category/stagcollective/", name: "Fxg-StagCollective" },
  "fxggxt-staghomme": { path: "/category/staghomme/", name: "Fxg-StagHomme" },
  "fxggxt-stickyrub": { path: "/category/say-uncle/stickyrub/", name: "Fxg-StickyRub" },
  "fxggxt-str8chaser": { path: "/category/str8chaser/", name: "Fxg-Str8Chaser" },
  "fxggxt-str8hell": { path: "/category/str8hell/", name: "Fxg-Str8Hell" },
  "fxggxt-tetatita": { path: "/category/tetatita/", name: "Fxg-Tetatita" },
  "fxggxt-thebronetwork": { path: "/category/thebronetwork/", name: "Fxg-TheBroNetwork" },
  "fxggxt-theguysite": { path: "/category/theguysite/", name: "Fxg-TheGuySite" },
  "fxggxt-twinktrade": { path: "/category/say-uncle/twinktrade/", name: "Fxg-TwinkTrade" },
  "fxggxt-uknakedmen": { path: "/category/uknakedmen/", name: "Fxg-UKNakedMen" },
  "fxggxt-uncuttwinks": { path: "/category/uncuttwinks/", name: "Fxg-UncutTwinks" },
  "fxggxt-varsitygrip": { path: "/category/say-uncle/varsitygrip/", name: "Fxg-VarsityGrip" },
  "fxggxt-voyr": { path: "/category/voyr/", name: "Fxg-VOYR" },
  "fxggxt-whynotbi": { path: "/category/whynotbi/", name: "Fxg-WhyNotBi" },
  "fxggxt-william-higgins": { path: "/category/william-higgins/", name: "Fxg-WilliamHiggins" },
  "fxggxt-xvideos-red": { path: "/category/xvideos-red/", name: "Fxg-XVideosRed" },
  "fxggxt-yesfather": { path: "/category/say-uncle/yesfather/", name: "Fxg-YesFather" },
  "fxggxt-youngbastards": { path: "/category/youngbastards/", name: "Fxg-YoungBastards" },
  "fxggxt-youngperps": { path: "/category/youngperps/", name: "Fxg-YoungPerps" },
};

export function buildFxggxtManifest(): StremioManifest {
  const catalogs: StremioManifest["catalogs"] = Object.entries(FXGGXT_CATALOG_MAP).map(([id, { name }]) => ({
    type: "movie",
    id,
    name,
    extra: [
      { name: "skip" },
    ],
  }));

  catalogs.unshift({
    type: "movie",
    id: "fxggxt-search",
    name: "Fxggxt Search",
    extra: [
      { name: "search", isRequired: true },
      { name: "skip" },
    ],
  });

  return {
    id: "community.fxggxt.stremio",
    version: "1.0.0",
    name: "Fxggxt",
    description: "Fxggxt content provider for Stremio - converted from Cloudstream 3 extension",
    resources: ["catalog", "meta", "stream"],
    types: ["movie"],
    catalogs,
    idPrefixes: ["fxggxt:"],
    behaviorHints: {
      adult: true,
      configurable: false,
    },
  };
}
